### ISSUE TITLE
TL Fragmenter error in APB Node

### ISSUE THREAD

**Issue by v-krvavac** [sifive/duh-scala#19] opened 2019-06-25 12:39 UTC
Error: 
requirement failed: TLFragmenter (with parent Some(sifive.blocks.rambusphy.NrambusphyTop@28852d6)) can't support fragmenting (1) to sub-beat (4) accesses

code:
  val PMA0APBNode: TLInwardNode = (
    imp.PMA0APBNode
      := TLToAPB(false)
      := TLBuffer()
      := TLFragmenter((8 / 8), c.blackbox.cacheBlockBytes, holdFirstDeny=true)
  )

When changing manually to 4, the error disappears.

**Comment by albertchen-sifive** [comment] 2019-09-17 16:21
duplicate of https://github.com/sifive/duh-scala/issues/32

**Closed as completed by albertchen-sifive** 2019-09-17 16:21 UTC
